PRODUCTS = [
    # ── Bypass Tools (XXA) ──────────────────────────────────────────
    {
        "slug": "under-door-tool",
        "sku": "PSV-XXA-1-1",
        "name": "Under-Door Bypass Tool",
        "category": "Bypass Tools",
        "price_cents": 2500,
        "price_display": "$25.00",
        "description_short": "Flexible under-door tool for lever handle bypass demonstrations.",
        "description_long": "A professional-grade flexible bypass tool designed for security research and training. Used to demonstrate the vulnerability of lever-handle doors without deadbolts to under-door attacks. Essential for physical penetration testing engagements.",
        "image": None,
        "in_stock": True,
        "featured": True,
    },
    {
        "slug": "shim-set",
        "sku": "PSV-XXA-2-1",
        "name": "Padlock Shim Set",
        "category": "Bypass Tools",
        "price_cents": 1500,
        "price_display": "$15.00",
        "description_short": "Set of padlock shims for bypass training and demonstrations.",
        "description_long": "A complete set of precision-cut padlock shims in multiple sizes. Ideal for teaching shim-based bypass techniques in controlled training environments. Includes a quick-start guide covering common padlock vulnerabilities.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "traveler-hook",
        "sku": "PSV-XXA-3-1",
        "name": "Traveler Hook",
        "category": "Bypass Tools",
        "price_cents": 3500,
        "price_display": "$35.00",
        "description_short": "Compact traveler hook for latch bypass and security assessments.",
        "description_long": "A compact, purpose-built traveler hook for demonstrating latch bypass techniques on improperly installed or vulnerable door hardware. Folds flat for easy transport. A staple tool in any physical security assessor's kit.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "latch-slip-set",
        "sku": "PSV-XXA-4-1",
        "name": "Latch Slip Set",
        "category": "Bypass Tools",
        "price_cents": 1800,
        "price_display": "$18.00",
        "description_short": "Assorted latch slips for spring bolt bypass on common door hardware.",
        "description_long": "A set of flexible latch slips in various widths and thicknesses, designed for bypassing spring-loaded latch bolts. Covers the most common commercial and residential door configurations. Includes a reference card with technique tips and compatible hardware profiles.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "bump-key-set",
        "sku": "PSV-XXA-5-1",
        "name": "Bump Key Set",
        "category": "Bypass Tools",
        "price_cents": 2200,
        "price_display": "$22.00",
        "description_short": "Set of bump keys for common residential and commercial keyways.",
        "description_long": "A curated set of bump keys covering the most widely deployed residential and commercial keyways in North America. Precision-cut for reliable bump technique demonstrations. For authorized security testing and training only.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "jiggler-key-set",
        "sku": "PSV-XXA-6-1",
        "name": "Jiggler Key Set",
        "category": "Bypass Tools",
        "price_cents": 1900,
        "price_display": "$19.00",
        "description_short": "Wafer lock jiggler keys for desk, cabinet, and automotive locks.",
        "description_long": "A set of jiggler keys designed for wafer-tumbler lock mechanisms commonly found in desks, filing cabinets, and older vehicle ignitions. Useful for demonstrating the inherent weaknesses of low-security wafer locks during training sessions.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    # ── Keys (XXB) ──────────────────────────────────────────────────
    {
        "slug": "elevator-key-set",
        "sku": "PSV-XXB-1-1",
        "name": "Elevator Key Set",
        "category": "Keys",
        "price_cents": 3200,
        "price_display": "$32.00",
        "description_short": "Common elevator override and access keys for security assessments.",
        "description_long": "A set of the most commonly encountered elevator override keys, including fire service, independent service, and phase-2 recall keys. Demonstrates the widespread issue of keyed-alike elevator access systems in commercial buildings. For authorized testing only.",
        "image": None,
        "in_stock": True,
        "featured": True,
    },
    {
        "slug": "heavy-equipment-key-set",
        "sku": "PSV-XXB-2-1",
        "name": "Heavy Equipment Key Set",
        "category": "Keys",
        "price_cents": 2800,
        "price_display": "$28.00",
        "description_short": "Universal keys for common construction and heavy equipment ignitions.",
        "description_long": "A set of keyed-alike ignition keys covering major heavy equipment manufacturers. Used to demonstrate how widely shared key patterns allow unauthorized operation of construction vehicles, forklifts, and industrial machinery during security assessments.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "utility-key-set",
        "sku": "PSV-XXB-3-1",
        "name": "Utility Key Set",
        "category": "Keys",
        "price_cents": 2500,
        "price_display": "$25.00",
        "description_short": "Keys for common utility panels, gates, and infrastructure access points.",
        "description_long": "A collection of widely shared utility keys used for electrical panels, water meter covers, gate locks, and other infrastructure access points. Highlights the systemic risk of keyed-alike utility access across municipalities and campuses.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "hvac-key-set",
        "sku": "PSV-XXB-4-1",
        "name": "HVAC Key Set",
        "category": "Keys",
        "price_cents": 2200,
        "price_display": "$22.00",
        "description_short": "Common HVAC and building system access keys for facility assessments.",
        "description_long": "A set of keys for common HVAC control panels, rooftop unit access, and building automation system enclosures. Demonstrates how shared HVAC key patterns can provide an entry vector into mechanical rooms and building management systems.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "cabinet-key-set",
        "sku": "PSV-XXB-5-1",
        "name": "Cabinet Key Set",
        "category": "Keys",
        "price_cents": 1800,
        "price_display": "$18.00",
        "description_short": "Common cabinet, desk, and filing cabinet keys for workplace assessments.",
        "description_long": "A set of the most common keyed-alike cabinet and desk keys found in office environments. Covers major furniture manufacturers' standard key patterns. Useful for demonstrating the false sense of security provided by standard office furniture locks.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    # ── Merch (XXC) ─────────────────────────────────────────────────
    {
        "slug": "psv-tshirt",
        "sku": "PSV-XXC-1-1",
        "name": "PSV Branded T-Shirt",
        "category": "Merch",
        "price_cents": 2800,
        "price_display": "$28.00",
        "description_short": "Official Physical Security Village t-shirt with running man logo.",
        "description_long": "Soft-blend tri-color t-shirt featuring the iconic PSV running man logo on the front and event history on the back. Available in multiple sizes. Show your support for the physical security community.",
        "image": None,
        "in_stock": True,
        "featured": True,
    },
    {
        "slug": "psv-patches",
        "sku": "PSV-XXC-2-1",
        "name": "PSV Patches (3-pack)",
        "category": "Merch",
        "price_cents": 1200,
        "price_display": "$12.00",
        "description_short": "Set of 3 embroidered PSV patches for bags, jackets, and lanyards.",
        "description_long": "Three embroidered patches featuring PSV branding and iconography. Iron-on or sew-on backing. Perfect for your conference bag, jacket, or lanyard collection. Each pack includes one large logo patch and two smaller accent patches.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "psv-stickers",
        "sku": "PSV-XXC-3-1",
        "name": "PSV Sticker Pack",
        "category": "Merch",
        "price_cents": 800,
        "price_display": "$8.00",
        "description_short": "Assorted pack of die-cut PSV stickers for laptops and gear.",
        "description_long": "A pack of 8 die-cut vinyl stickers featuring PSV logos, slogans, and original artwork from the physical security community. Weatherproof and scratch-resistant. Deck out your laptop, water bottle, or pelican case.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "psv-challenge-coin",
        "sku": "PSV-XXC-4-1",
        "name": "PSV Challenge Coin",
        "category": "Merch",
        "price_cents": 1500,
        "price_display": "$15.00",
        "description_short": "Collectible PSV challenge coin with dual-sided embossed design.",
        "description_long": "A heavy, dual-sided challenge coin featuring the PSV running man logo on the front and an original lock mechanism engraving on the reverse. Antique brass finish with enamel fill. A must-have collectible for conference attendees and physical security enthusiasts.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    # ── RFID (XXD) ──────────────────────────────────────────────────
    {
        "slug": "lf-rfid-fobs",
        "sku": "PSV-XXD-1-1",
        "name": "LF RFID Key Fobs — T5557 (5-pack)",
        "category": "RFID",
        "price_cents": 1800,
        "price_display": "$18.00",
        "description_short": "5 writable 125kHz T5557 key fobs for low-frequency RFID research.",
        "description_long": "Five T5557 writable low-frequency (125kHz) RFID key fobs. Compatible with most LF access control systems and capable of emulating HID, EM4100, and other common credential formats. Works with Proxmark, Flipper Zero, and other RFID tools.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "hf-rfid-fobs",
        "sku": "PSV-XXD-2-1",
        "name": 'HF RFID Key Fobs — Mifare Classic "Magic" 1K (5-pack)',
        "category": "RFID",
        "price_cents": 2400,
        "price_display": "$24.00",
        "description_short": "5 writable 13.56MHz Mifare Classic Magic 1K key fobs for HF RFID research.",
        "description_long": 'Five "Magic" generation 1a Mifare Classic 1K key fobs operating at 13.56MHz. Block 0 is writable, allowing full UID and manufacturer data cloning. Ideal for access control research and demonstrating Mifare Classic vulnerabilities.',
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "proxmark3-ez",
        "sku": "PSV-XXD-3-1",
        "name": "Proxmark 3 EZ",
        "category": "RFID",
        "price_cents": 7500,
        "price_display": "$75.00",
        "description_short": "Entry-level Proxmark 3 for RFID research and access control testing.",
        "description_long": "The Proxmark 3 EZ is an accessible entry point into RFID security research. Supports reading, writing, and emulating both low-frequency (125kHz) and high-frequency (13.56MHz) credentials. Comes pre-flashed with the latest Iceman firmware and includes a USB-C cable and antenna set.",
        "image": None,
        "in_stock": True,
        "featured": True,
    },
    {
        "slug": "rfid-shielding-sleeves",
        "sku": "PSV-XXD-4-1",
        "name": "RFID Shielding Sleeves (10-pack)",
        "category": "RFID",
        "price_cents": 1000,
        "price_display": "$10.00",
        "description_short": "Faraday sleeves to protect access cards and fobs from unauthorized reads.",
        "description_long": "A pack of 10 RFID-blocking Faraday sleeves sized for standard access cards and key fobs. Prevents unauthorized skimming and relay attacks on contactless credentials. A simple, effective countermeasure to demonstrate during security awareness training.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    # ── Misc (XXE) ──────────────────────────────────────────────────
    {
        "slug": "tamper-evident-kit",
        "sku": "PSV-XXE-1-1",
        "name": "Tamper-Evident Seal Sample Kit",
        "category": "Misc",
        "price_cents": 2200,
        "price_display": "$22.00",
        "description_short": "Assorted tamper-evident seals and labels for security training.",
        "description_long": "A sample kit of tamper-evident seals, labels, and tape used in shipping, evidence handling, and physical security. Includes examples of common defeat methods and a guide to identifying tampered seals. Great for training and awareness programs.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
    {
        "slug": "pentest-field-notebook",
        "sku": "PSV-XXE-2-1",
        "name": "Pentest Field Notebook",
        "category": "Misc",
        "price_cents": 1400,
        "price_display": "$14.00",
        "description_short": "Rugged, water-resistant notebook with physical assessment templates.",
        "description_long": "A pocket-sized, water-resistant field notebook pre-printed with physical penetration testing templates: door hardware checklists, access control audit forms, tailgating observation logs, and photo reference pages. Lay-flat binding with durable cover.",
        "image": None,
        "in_stock": True,
        "featured": False,
    },
]


def get_all_products():
    return PRODUCTS


def get_product_by_slug(slug):
    for product in PRODUCTS:
        if product["slug"] == slug:
            return product
    return None


def get_categories():
    return sorted({p["category"] for p in PRODUCTS})


def get_featured_products():
    return [p for p in PRODUCTS if p.get("featured")]
